// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailableVersions() {
  return window['go']['main']['App']['GetAvailableVersions']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetGlobalNpmPackages() {
  return window['go']['main']['App']['GetGlobalNpmPackages']();
}

export function GetVersionList() {
  return window['go']['main']['App']['GetVersionList']();
}

export function InstallVersion(arg1) {
  return window['go']['main']['App']['InstallVersion'](arg1);
}

export function IsNvmAvailable() {
  return window['go']['main']['App']['IsNvmAvailable']();
}

export function UninstallGlobalNpmPackage(arg1) {
  return window['go']['main']['App']['UninstallGlobalNpmPackage'](arg1);
}

export function UninstallVersion(arg1) {
  return window['go']['main']['App']['UninstallVersion'](arg1);
}

export function UseVersion(arg1) {
  return window['go']['main']['App']['UseVersion'](arg1);
}
