// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAvailableVersions():Promise<Array<main.RemoteVersion>>;

export function GetCurrentVersion():Promise<main.CurrentInfo>;

export function GetGlobalNpmPackages():Promise<Array<main.GlobalNpmPackage>>;

export function GetVersionList():Promise<Array<main.NodeVersion>>;

export function InstallVersion(arg1:string):Promise<void>;

export function IsNvmAvailable():Promise<boolean>;

export function UninstallGlobalNpmPackage(arg1:string):Promise<void>;

export function UninstallVersion(arg1:string):Promise<void>;

export function UseVersion(arg1:string):Promise<void>;
